@RAD_Lab2_Part5_HostAddress = https://localhost:7262

GET {{RAD_Lab2_Part5_HostAddress}}/adlist

###

GET {{RAD_Lab2_Part5_HostAddress}}/adlist/categorylist

###

GET {{RAD_Lab2_Part5_HostAddress}}/adlist/sellerlist

###

POST {{RAD_Lab2_Part5_HostAddress}}/adlist/categorylist
Content-Type: application/json

{
  "Name":"Movie"
}

###

POST {{RAD_Lab2_Part5_HostAddress}}/adlist/sellerlist
Content-Type: application/json

{
  "SellerName": "George Lucas"
}

###

POST {{RAD_Lab2_Part5_HostAddress}}/adlist
Content-Type: application/json

{
  "Description": "Star Wars: Revenge of the Sith",
  "SellerId": 1,
  "CategoryId": 1
}

###